data = [
    # Positive
    ("product is good", "Positive"),
    ("delivery was fast", "Positive"),
    ("excellent quality", "Positive"),
    ("very happy with the product", "Positive"),
    ("great value for money", "Positive"),
    ("love the product", "Positive"),
    ("nice packaging", "Positive"),
    ("friendly customer service", "Positive"),
    ("helpful support team", "Positive"),
        ("delicious food", "Positive"),
        ("clean and comfortable", "Positive"),
        ("enjoyed my purchase", "Positive"),
        ("satisfied with the product", "Positive"),
        ("happy with the service", "Positive"),
        ("would recommend to others", "Positive"),
        ("fast delivery", "Positive"),
    ("amazing experience", "Positive"),
    ("product is excellent", "Positive"),
    ("very satisfied", "Positive"),
    ("product is bad", "Negative"),
    ("delivery was slow", "Negative"),
    ("very poor quality", "Negative"),
    ("not satisfied", "Negative"),
    ("too expensive", "Negative"),
    ("worst product ever", "Negative"),
        ("rude customer service", "Negative"),
        ("unhelpful support team", "Negative"),
        ("disgusting food", "Negative"),
        ("dirty and uncomfortable", "Negative"),
        ("horrible experience", "Negative"),
        ("unsatisfied with the product", "Negative"),
        ("unhappy with the service", "Negative"),
        ("would avoid in the future", "Negative"),
        ("late delivery", "Negative"),
        ("terrible quality", "Negative"),
    ("product is okay", "Neutral"),
    ("average quality", "Neutral"),
    ("delivery was fine", "Neutral"),
    ("not bad but not great", "Neutral"),
    ("satisfactory experience", "Neutral"),
    ("product is decent", "Neutral"),
        ("customer service was okay", "Neutral"),
        ("support team was average", "Neutral"),
        ("food was fine", "Neutral"),
        ("clean but not comfortable", "Neutral"),
        ("experience was so-so", "Neutral"),
        ("product is acceptable", "Neutral"),
        ("service was mediocre", "Neutral"),
        ("would consider buying again", "Neutral"),
        ("delivery was on time", "Neutral"),
        ("great product", "Positive"),
("excellent quality", "Positive"),
("loved it", "Positive"),
("very good", "Positive"),
("works perfectly", "Positive"),
("super fast delivery", "Positive"),
("nice packaging", "Positive"),
("highly recommended", "Positive"),
("value for money", "Positive"),
("impressed with the quality", "Positive"),
("very happy with my purchase", "Positive"),
("fantastic experience", "Positive"),
("awesome product", "Positive"),
("good customer support", "Positive"),
("quick response from support", "Positive"),
("easy to use app", "Positive"),
("smooth experience", "Positive"),
("great service", "Positive"),
("perfect condition", "Positive"),
("very reliable", "Positive"),
("looks premium", "Positive"),
("good design", "Positive"),
("worth buying", "Positive"),
("totally satisfied", "Positive"),
("better than expected", "Positive"),
("works as described", "Positive"),
("very efficient", "Positive"),
("fast and secure delivery", "Positive"),
("neat packaging", "Positive"),
("easy checkout process", "Positive"),
("bad product", "Negative"),
("very disappointing", "Negative"),
("waste of money", "Negative"),
("not worth it", "Negative"),
("poor performance", "Negative"),
("slow delivery", "Negative"),
("damaged packaging", "Negative"),
("terrible experience", "Negative"),
("very bad quality", "Negative"),
("not working properly", "Negative"),
("cheap material", "Negative"),
("very slow app", "Negative"),
("app crashes frequently", "Negative"),
("bad user interface", "Negative"),
("support was useless", "Negative"),
("no response from customer care", "Negative"),
("rude staff", "Negative"),
("product stopped working", "Negative"),
("overpriced item", "Negative"),
("wrong product delivered", "Negative"),
("late delivery", "Negative"),
("poor packaging", "Negative"),
("unacceptable service", "Negative"),
("not satisfied at all", "Negative"),
("very frustrating experience", "Negative"),
("quality is terrible", "Negative"),
("delivery took too long", "Negative"),
("broken item received", "Negative"),
("very unreliable", "Negative"),
("not recommended", "Negative"),
("average product", "Neutral"),
("okay quality", "Neutral"),
("delivery was acceptable", "Neutral"),
("not great but not bad", "Neutral"),
("mediocre experience", "Neutral"),
("product is fine", "Neutral"),
("customer service was average", "Neutral"),
("support team was okay", "Neutral"),
("food was decent", "Neutral"),
("clean but not comfortable", "Neutral"),
("experience was average", "Neutral"),
("product is acceptable", "Neutral"),
("service was mediocre", "Neutral"),
("would consider buying again", "Neutral"),
("delivery was on time", "Neutral"),
("it is okay", "Neutral"),
("average product", "Neutral"),
("nothing special", "Neutral"),
("works fine", "Neutral"),
("just okay", "Neutral"),
("quality is average", "Neutral"),
("delivery was normal", "Neutral"),
("experience was fine", "Neutral"),
("not too bad", "Neutral"),
("acceptable quality", "Neutral"),
("meets expectations", "Neutral"),
("price is reasonable", "Neutral"),
("standard packaging", "Neutral"),
("app is usable", "Neutral"),
("service was okay", "Neutral"),
("nothing impressive", "Neutral"),
("moderate performance", "Neutral"),
("fair enough", "Neutral"),
("it does the job", "Neutral"),
("no major issues", "Neutral"),
("product is decent", "Neutral"),
("average experience", "Neutral"),
("okay for the price", "Neutral"),
("not great not bad", "Neutral"),
("delivery was on time", "Neutral"),
("basic features only", "Neutral"),
("satisfactory", "Neutral"),
("fine for daily use", "Neutral"),
("neither good nor bad", "Neutral"),
("just average", "Neutral"),
# Positive
("packaging was very good", "Positive"),
("well packed product", "Positive"),
("secure packaging", "Positive"),
("nice and neat packaging", "Positive"),
("product arrived safely packed", "Positive"),
("impressive packaging quality", "Positive"),

# Negative
("packaging was damaged", "Negative"),
("poor packaging", "Negative"),
("box was torn", "Negative"),
("bad packaging quality", "Negative"),
("product was not packed properly", "Negative"),
("cheap packaging", "Negative"),

# Neutral
("packaging was okay", "Neutral"),
("average packaging", "Neutral"),
("standard packaging", "Neutral"),
("nothing special about packaging", "Neutral"),
("packaging was fine", "Neutral"),
# Positive
("fast delivery", "Positive"),
("delivery was very quick", "Positive"),
("received earlier than expected", "Positive"),
("on time delivery", "Positive"),
("smooth delivery experience", "Positive"),
("quick shipping", "Positive"),

# Negative
("delivery was late", "Negative"),
("very slow delivery", "Negative"),
("delayed delivery", "Negative"),
("delivery took too long", "Negative"),
("package arrived late", "Negative"),
("bad delivery service", "Negative"),

# Neutral
("delivery was okay", "Neutral"),
("delivery was fine", "Neutral"),
("average delivery time", "Neutral"),
("delivery was as expected", "Neutral"),
("nothing special about delivery", "Neutral"),
("it is okay", "Neutral"),
("average product", "Neutral"),
("nothing special", "Neutral"),
("works fine", "Neutral"),
("just okay", "Neutral"),
("quality is average", "Neutral"),
("delivery was normal", "Neutral"),
("experience was fine", "Neutral"),
("not too bad", "Neutral"),
("acceptable quality", "Neutral"),
("meets expectations", "Neutral"),
("price is reasonable", "Neutral"),
("standard packaging", "Neutral"),
("app is usable", "Neutral"),
("service was okay", "Neutral"),
("nothing impressive", "Neutral"),
("moderate performance", "Neutral"),
("fair enough", "Neutral"),
("it does the job", "Neutral"),
("no major issues", "Neutral"),
("product is decent", "Neutral"),
("average experience", "Neutral"),
("okay for the price", "Neutral"),
("not great not bad", "Neutral"),
("delivery was on time", "Neutral"),
("basic features only", "Neutral"),
("satisfactory", "Neutral"),
("fine for daily use", "Neutral"),
("neither good nor bad", "Neutral"),
("just average", "Neutral"),
# Positive
("app is easy to use", "Positive"),
("smooth app experience", "Positive"),
("website is fast", "Positive"),
("user friendly interface", "Positive"),
("good app design", "Positive"),
("easy navigation", "Positive"),

# Negative
("app keeps crashing", "Negative"),
("website is slow", "Negative"),
("bad user experience", "Negative"),
("app is buggy", "Negative"),
("difficult to navigate", "Negative"),
("poor interface design", "Negative"),
("faced alot of issues with the app", "Negative"),
("website is unresponsive", "Negative"),
("faced a lot of issues with the website", "Negative"),
("it is laggy", "Negative"),
("UI is not intuitive", "Negative"),
("UI is confusing", "Negative"),

# Neutral
("app is okay", "Neutral"),
("website experience is average", "Neutral"),
("app works fine", "Neutral"),
("nothing special about the app", "Neutral"),
("interface is normal", "Neutral"),

]