data = [
        ("Delivery was late", ["Delivery"]),
        ("product quality is amazing", ["Product_Quality"]),
        ("Price is too high", ["Price"]),
        ("Packaging was bad", ["Packaging"]),
        ("customer support was helpful", ["Customer_Service"]),
        ("app is slow", ["App_Experience"]),
        ("Delivery was late", ["Delivery"]),
    ("Delivery arrived late", ["Delivery"]),
    ("my Delivery was delayed", ["Delivery"]),
    ("late Delivery service", ["Delivery"]),
    ("Delivery took too long", ["Delivery"]),
    ("Delivery was late", ["Delivery"]),
    ("Delivery arrived late", ["Delivery"]),
    ("my Delivery was delayed", ["Delivery"]),
    ("late Delivery service", ["Delivery"]),
    ("Delivery took too long", ["Delivery"]),
    ("Delivery was slow", ["Delivery"]),
    ("slow Delivery", ["Delivery"]),
    ("shipping was very slow", ["Delivery"]),
    ("Delivery took many days", ["Delivery"]),
    ("Delivery is extremely slow", ["Delivery"]),
    ("i received my order late", ["Delivery"]),
    ("my order came very late", ["Delivery"]),
    ("order Delivery was delayed", ["Delivery"]),
    ("got my order on time", ["Delivery"]),
    ("order arrived quickly", ["Delivery"]),
    ("product is good", ["Product_Quality"]),
    ("product quality is good", ["Product_Quality"]),
    ("product is bad", ["Product_Quality"]),
    ("poor product quality", ["Product_Quality"]),
    ("excellent product quality", ["Product_Quality"]),
    ("product is good", ["Product_Quality"]),
    ("product quality is good", ["Product_Quality"]),
    ("product is bad", ["Product_Quality"]),
    ("poor product quality", ["Product_Quality"]),
    ("excellent product quality", ["Product_Quality"]),
    ("very good quality product", ["Product_Quality"]),
    ("amazing product quality", ["Product_Quality"]),
    ("excellent item", ["Product_Quality"]),
    ("product is शानदार", ["Product_Quality"]),
    ("really satisfied with the product", ["Product_Quality"]),
    ("product quality is poor", ["Product_Quality"]),
    ("very bad product", ["Product_Quality"]),
    ("item is खराब", ["Product_Quality"]),
    ("product broke quickly", ["Product_Quality"]),
    ("low quality item", ["Product_Quality"]),
    ("product quality is poor", ["Product_Quality"]),
    ("very bad product", ["Product_Quality"]),
    ("item is खराब", ["Product_Quality"]),
    ("product broke quickly", ["Product_Quality"]),
    ("low quality item", ["Product_Quality"]),
    ("product stopped working", ["Product_Quality"]),
    ("item is not working properly", ["Product_Quality"]),
    ("product is defective", ["Product_Quality"]),
    ("product is damaged", ["Product_Quality"]),
    ("item doesn't function well", ["Product_Quality"]),
    ("this product is worth it", ["Product_Quality"]),
    ("not satisfied with the product", ["Product_Quality"]),
    ("product quality could be better", ["Product_Quality"]),
    ("i love this product", ["Product_Quality"]),
    ("this item is terrible", ["Product_Quality"]),
    ("Price is high", ["Price"]),
    ("Price is too high", ["Price"]),
    ("Price is low", ["Price"]),
    ("Price is reasonable", ["Price"]),
    ("Price is affordable", ["Price"]),
    ("very expensive product", ["Price"]),
    ("too costly", ["Price"]),
    ("Price is not worth it", ["Price"]),
    ("overPriced item", ["Price"]),
    ("high Price for this product", ["Price"]),
    ("cheap product", ["Price"]),
    ("very affordable Price", ["Price"]),
    ("low cost item", ["Price"]),
    ("budget friendly product", ["Price"]),
    ("great Price for the product", ["Price"]),
    ("value for money", ["Price"]),
    ("not worth the Price", ["Price"]),
    ("worth the money", ["Price"]),
    ("good value for money", ["Price"]),
    ("bad value for money", ["Price"]),
    ("this product is too expensive", ["Price"]),
    ("i think the Price is fair", ["Price"]),
    ("Price could be lower", ["Price"]),
    ("not satisfied with the Price", ["Price"]),
    ("Price is justified", ["Price"]),
    ("Packaging was good", ["Packaging"]),
    ("Packaging was bad", ["Packaging"]),
    ("poor Packaging", ["Packaging"]),
    ("excellent Packaging", ["Packaging"]),
    ("Packaging was good", ["Packaging"]),
    ("Packaging was bad", ["Packaging"]),
    ("poor Packaging", ["Packaging"]),
    ("excellent Packaging", ["Packaging"]),
    ("very good Packaging", ["Packaging"]),
    ("amazing Packaging", ["Packaging"]),
    ("excellent box", ["Packaging"]),
    ("package was damaged", ["Packaging"]),
    ("box was broken", ["Packaging"]),
    ("item was not well packaged", ["Packaging"]),
    ("package arrived in good condition", ["Packaging"]),
    ("box was intact and secure", ["Packaging"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("customer support was bad", ["Customer_Service"]),
    ("poor customer service", ["Customer_Service"]),
    ("excellent customer service", ["Customer_Service"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("customer support was bad", ["Customer_Service"]),
    ("poor customer service", ["Customer_Service"]),
    ("excellent customer service", ["Customer_Service"]),
    ("very good customer service", ["Customer_Service"]),
    ("amazing customer support", ["Customer_Service"]),
    ("support team was excellent", ["Customer_Service"]),
    ("support team was unhelpful", ["Customer_Service"]),
    ("not satisfied with customer service", ["Customer_Service"]),
    ("i had a great experience with customer support", ["Customer_Service"]),
    ("the support team was terrible", ["Customer_Service"]),
    ("app is slow", ["App_Experience"]),
    ("Delivery was late", ["Delivery"]),
        ("product quality is amazing", ["Product_Quality"]),
        ("Price is too high", ["Price"]),
        ("Packaging was bad", ["Packaging"]),
        ("customer support was helpful", ["Customer_Service"]),
        ("app is slow", ["App_Experience"]),
        ("Delivery was late", ["Delivery"]),
    ("Delivery arrived late", ["Delivery"]),
    ("my Delivery was delayed", ["Delivery"]),
    ("late Delivery service", ["Delivery"]),
    ("Delivery took too long", ["Delivery"]),
    ("Delivery was late", ["Delivery"]),
    ("Delivery arrived late", ["Delivery"]),
    ("my Delivery was delayed", ["Delivery"]),
    ("late Delivery service", ["Delivery"]),
    ("Delivery took too long", ["Delivery"]),
    ("Delivery was slow", ["Delivery"]),
    ("slow Delivery", ["Delivery"]),
    ("shipping was very slow", ["Delivery"]),
    ("Delivery took many days", ["Delivery"]),
    ("Delivery is extremely slow", ["Delivery"]),
    ("i received my order late", ["Delivery"]),
    ("my order came very late", ["Delivery"]),
    ("order Delivery was delayed", ["Delivery"]),
    ("got my order on time", ["Delivery"]),
    ("order arrived quickly", ["Delivery"]),
    ("product is good", ["Product_Quality"]),
    ("product quality is good", ["Product_Quality"]),
    ("product is bad", ["Product_Quality"]),
    ("poor product quality", ["Product_Quality"]),
    ("excellent product quality", ["Product_Quality"]),
    ("product is good", ["Product_Quality"]),
    ("product quality is good", ["Product_Quality"]),
    ("product is bad", ["Product_Quality"]),
    ("poor product quality", ["Product_Quality"]),
    ("excellent product quality", ["Product_Quality"]),
    ("very good quality product", ["Product_Quality"]),
    ("amazing product quality", ["Product_Quality"]),
    ("excellent item", ["Product_Quality"]),
    ("product is शानदार", ["Product_Quality"]),
    ("really satisfied with the product", ["Product_Quality"]),
    ("product quality is poor", ["Product_Quality"]),
    ("very bad product", ["Product_Quality"]),
    ("item is खराब", ["Product_Quality"]),
    ("product broke quickly", ["Product_Quality"]),
    ("low quality item", ["Product_Quality"]),
    ("product quality is poor", ["Product_Quality"]),
    ("very bad product", ["Product_Quality"]),
    ("item is खराब", ["Product_Quality"]),
    ("product broke quickly", ["Product_Quality"]),
    ("low quality item", ["Product_Quality"]),
    ("product stopped working", ["Product_Quality"]),
    ("item is not working properly", ["Product_Quality"]),
    ("product is defective", ["Product_Quality"]),
    ("product is damaged", ["Product_Quality"]),
    ("item doesn't function well", ["Product_Quality"]),
    ("this product is worth it", ["Product_Quality"]),
    ("not satisfied with the product", ["Product_Quality"]),
    ("product quality could be better", ["Product_Quality"]),
    ("i love this product", ["Product_Quality"]),
    ("this item is terrible", ["Product_Quality"]),
    ("Price is high", ["Price"]),
    ("Price is too high", ["Price"]),
    ("Price is low", ["Price"]),
    ("Price is reasonable", ["Price"]),
    ("Price is affordable", ["Price"]),
    ("very expensive product", ["Price"]),
    ("too costly", ["Price"]),
    ("Price is not worth it", ["Price"]),
    ("overPriced item", ["Price"]),
    ("high Price for this product", ["Price"]),
    ("cheap product", ["Price"]),
    ("very affordable Price", ["Price"]),
    ("low cost item", ["Price"]),
    ("budget friendly product", ["Price"]),
    ("great Price for the product", ["Price"]),
    ("value for money", ["Price"]),
    ("not worth the Price", ["Price"]),
    ("worth the money", ["Price"]),
    ("good value for money", ["Price"]),
    ("bad value for money", ["Price"]),
    ("this product is too expensive", ["Price"]),
    ("i think the Price is fair", ["Price"]),
    ("Price could be lower", ["Price"]),
    ("not satisfied with the Price", ["Price"]),
    ("Price is justified", ["Price"]),
    ("Packaging was good", ["Packaging"]),
    ("Packaging was bad", ["Packaging"]),
    ("poor Packaging", ["Packaging"]),
    ("excellent Packaging", ["Packaging"]),
    ("Packaging was good", ["Packaging"]),
    ("Packaging was bad", ["Packaging"]),
    ("poor Packaging", ["Packaging"]),
    ("excellent Packaging", ["Packaging"]),
    ("very good Packaging", ["Packaging"]),
    ("amazing Packaging", ["Packaging"]),
    ("excellent box", ["Packaging"]),
    ("package was damaged", ["Packaging"]),
    ("box was broken", ["Packaging"]),
    ("item was not well packaged", ["Packaging"]),
    ("package arrived in good condition", ["Packaging"]),
    ("box was intact and secure", ["Packaging"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("customer support was bad", ["Customer_Service"]),
    ("poor customer service", ["Customer_Service"]),
    ("excellent customer service", ["Customer_Service"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("customer support was bad", ["Customer_Service"]),
    ("poor customer service", ["Customer_Service"]),
    ("excellent customer service", ["Customer_Service"]),
    ("very good customer service", ["Customer_Service"]),
    ("amazing customer support", ["Customer_Service"]),
    ("support team was excellent", ["Customer_Service"]),
    ("support team was unhelpful", ["Customer_Service"]),
    ("not satisfied with customer service", ["Customer_Service"]),
    ("i had a great experience with customer support", ["Customer_Service"]),
    ("the support team was terrible", ["Customer_Service"]),
    ("app is slow", ["App_Experience"]),
    ("app is fast", ["App_Experience"]),
    ("app is unresponsive", ["App_Experience"]),
    ("app is user-friendly", ["App_Experience"]),
    ("app is slow", ["App_Experience"]),
    ("app is fast", ["App_Experience"]),
    ("app is unresponsive", ["App_Experience"]),
    ("app is user-friendly", ["App_Experience"]),
    ("very slow app performance", ["App_Experience"]),
    ("amazing app experience", ["App_Experience"]),
    ("the app crashes frequently", ["App_Experience"]),
    ("the app is easy to navigate", ["App_Experience"]),
    ("website is slow", ["App_Experience"]),
    ("website is fast", ["App_Experience"]),    
    ("website is unresponsive", ["App_Experience"]),
    ("website is user-friendly", ["App_Experience"]),
    ("website is slow", ["App_Experience"]),
    ("website is fast", ["App_Experience"]),    
    ("website is unresponsive", ["App_Experience"]),
    ("website is user-friendly", ["App_Experience"]),
    ("very slow website performance", ["App_Experience"]),
    ("amazing website experience", ["App_Experience"]),
    ("the website crashes frequently", ["App_Experience"]),
    ("the website is easy to navigate", ["App_Experience"]),
    ("website is very slow", ["App_Experience"]),
    ("app is very slow", ["App_Experience"]),   
    ("app is extremely slow", ["App_Experience"]),
    ("website is extremely slow", ["App_Experience"]),
    # new data
    ("the price feels a bit high for what you get", ["Price"]),
    ("I expected this to be cheaper", ["Price"]),
    ("it's reasonably priced compared to competitors", ["Price"]),
    ("not worth the price in my opinion", ["Price"]),
    ("the pricing seems fair for the quality", ["Price"]),
    ("I think this is overpriced", ["Price"]),
    ("good value for the money", ["Price"]),
    ("the cost doesn't justify the product", ["Price"]),
    ("pricing is acceptable but not great", ["Price"]),
    ("this is too expensive for everyday use", ["Price"]),
    ("I found similar products at a lower price", ["Price"]),
    ("the price could definitely be lower", ["Price"]),
    ("worth every penny", ["Price"]),
    ("I regret paying this much", ["Price"]),
    ("it's priced competitively", ["Price"]),
    ("the pricing seems a bit steep for this product", ["Price"]),
    ("I feel like I paid more than I should have", ["Price"]),
    ("this doesn't justify its price tag", ["Price"]),
    ("the cost is slightly higher than expected", ["Price"]),
    ("it's not cheap, but the quality makes up for it", ["Price"]),
    ("I think the price could be more competitive", ["Price"]),
    ("it's priced higher than similar products", ["Price"]),
    ("the product feels overpriced for its features", ["Price"]),
    ("I would consider buying again if the price drops", ["Price"]),
    ("it's affordable compared to other options", ["Price"]),
    ("the discount made it worth buying", ["Price"]),
    ("even on sale, it feels expensive", ["Price"]),
    ("pricing is inconsistent across the platform", ["Price"]),
    ("I expected better value at this price point", ["Price"]),
    ("the product delivers good value overall", ["Price"]),
    ("it's expensive but delivers what it promises", ["Price"]),
    ("the price increase is noticeable", ["Price"]),
    ("this used to be cheaper before", ["Price"]),
    ("the price doesn't match the experience", ["Price"]),
    ("it's a bit pricey for regular use", ["Price"]),
    ("my order arrived later than expected", ["Delivery"]),
    ("delivery was quicker than I thought", ["Delivery"]),
    ("it took too long to receive the product", ["Delivery"]),
    ("the package arrived right on time", ["Delivery"]),
    ("delivery delays were frustrating", ["Delivery"]),
    ("I received my order earlier than scheduled", ["Delivery"]),
    ("shipping was slower than advertised", ["Delivery"]),
    ("the delivery process was smooth", ["Delivery"]),
    ("my order got delayed without any update", ["Delivery"]),
    ("it arrived within the promised time frame", ["Delivery"]),
    ("delivery timing was inaccurate", ["Delivery"]),
    ("I had to wait longer than expected", ["Delivery"]),
    ("the item was delivered promptly", ["Delivery"]),
    ("delivery experience was disappointing", ["Delivery"]),
    ("no issues with delivery, it was on time", ["Delivery"]),
    ("the delivery was delayed without any explanation", ["Delivery"]),
    ("I received the item much sooner than expected", ["Delivery"]),
    ("delivery took longer than promised", ["Delivery"]),
    ("the order was delivered exactly on schedule", ["Delivery"]),
    ("there was a significant delay in shipping", ["Delivery"]),
    ("my package arrived earlier than the estimated date", ["Delivery"]),
    ("delivery updates were not accurate", ["Delivery"]),
    ("the delivery process was seamless", ["Delivery"]),
    ("I had to follow up multiple times for delivery", ["Delivery"]),
    ("delivery was handled efficiently", ["Delivery"]),
    ("the item was stuck in transit for days", ["Delivery"]),
    ("it arrived just in time", ["Delivery"]),
    ("delivery was quicker than usual", ["Delivery"]),
    ("there was no delay in delivery", ["Delivery"]),
    ("I didn't receive my order on time", ["Delivery"]),
    ("delivery timing was unreliable", ["Delivery"]),
    ("the courier arrived late", ["Delivery"]),
    ("my order was delivered without any issues", ["Delivery"]),
    ("shipping speed was impressive", ["Delivery"]),
    ("delivery took longer than expected due to delays", ["Delivery"]),
    ("the packaging was secure and well done", ["Packaging"]),
    ("the box arrived damaged", ["Packaging"]),
    ("packaging could have been better", ["Packaging"]),
    ("everything was packed neatly", ["Packaging"]),
    ("the product was not properly protected", ["Packaging"]),
    ("the packaging looked cheap", ["Packaging"]),
    ("the item was safely packaged", ["Packaging"]),
    ("the box was crushed on arrival", ["Packaging"]),
    ("packaging quality was impressive", ["Packaging"]),
    ("the product was loosely packed", ["Packaging"]),
    ("it came in perfect condition", ["Packaging"]),
    ("the packaging didn't protect the item", ["Packaging"]),
    ("well packed and sealed", ["Packaging"]),
    ("the packaging was strong and protective", ["Packaging"]),
    ("the item arrived with damaged packaging", ["Packaging"]),
    ("packaging was minimal but sufficient", ["Packaging"]),
    ("the product was packed very carefully", ["Packaging"]),
    ("the box was torn when it arrived", ["Packaging"]),
    ("packaging quality could be improved", ["Packaging"]),
    ("everything inside was well secured", ["Packaging"]),
    ("the packaging didn't prevent damage", ["Packaging"]),
    ("it was packed in a sturdy box", ["Packaging"]),
    ("the packaging looked premium", ["Packaging"]),
    ("the item was poorly wrapped", ["Packaging"]),
    ("the box was slightly damaged but the product was fine", ["Packaging"]),
    ("packaging was neat and professional", ["Packaging"]),
    ("the product came in loose packaging", ["Packaging"]),
    ("it was packaged with care", ["Packaging"]),
    ("the packaging felt cheap", ["Packaging"]),
    ("there was no proper cushioning inside", ["Packaging"]),
    ("the product was securely sealed", ["Packaging"]),
    ("packaging was damaged during transit", ["Packaging"]),
    ("everything was intact and well packed", ["Packaging"]),
    ("the app takes too long to load", ["App_Experience"]),
    ("navigation is smooth and intuitive", ["App_Experience"]),
    ("the website feels slow at times", ["App_Experience"]),
    ("I had trouble completing my order", ["App_Experience"]),
    ("the interface is user friendly", ["App_Experience"]),
    ("the app crashes occasionally", ["App_Experience"]),
    ("checkout process was confusing", ["App_Experience"]),
    ("everything works as expected", ["App_Experience"]),
    ("the website is responsive and fast", ["App_Experience"]),
    ("I experienced several glitches", ["App_Experience"]),
    ("the design is clean and easy to use", ["App_Experience"]),
    ("pages take too long to load", ["App_Experience"]),
    ("the app freezes sometimes", ["App_Experience"]),
    ("overall experience is smooth", ["App_Experience"]),
    ("the app responds slowly at times", ["App_Experience"]),
    ("I had no issues using the app", ["App_Experience"]),
    ("the website loads quickly and works well", ["App_Experience"]),
    ("I faced issues while placing an order", ["App_Experience"]),
    ("the app interface is confusing", ["App_Experience"]),
    ("navigation could be improved", ["App_Experience"]),
    ("everything works smoothly on the app", ["App_Experience"]),
    ("the website crashes occasionally", ["App_Experience"]),
    ("it takes too long to complete simple actions", ["App_Experience"]),
    ("the app is easy to navigate", ["App_Experience"]),
    ("the user experience is frustrating", ["App_Experience"]),
    ("pages take time to load", ["App_Experience"]),
    ("the app freezes during checkout", ["App_Experience"]),
    ("the overall experience is good", ["App_Experience"]),
    ("the design feels outdated", ["App_Experience"]),
    ("the app performs consistently well", ["App_Experience"]),
    ("I encountered several bugs", ["App_Experience"]),
    ("the website works fine on my device", ["App_Experience"]),
    ("checkout process is smooth", ["App_Experience"]),
    ("the app lags frequently", ["App_Experience"]),
    ("customer support resolved my issue quickly", ["Customer_Service"]),
    ("I had a bad experience with customer service", ["Customer_Service"]),
    ("the support team was responsive and helpful", ["Customer_Service"]),
    ("it took too long to get a response", ["Customer_Service"]),
    ("customer service was polite and professional", ["Customer_Service"]),
    ("my issue was not handled properly", ["Customer_Service"]),
    ("support was quick and efficient", ["Customer_Service"]),
    ("I didn't get any help from support", ["Customer_Service"]),
    ("the response time was impressive", ["Customer_Service"]),
    ("customer service could be better", ["Customer_Service"]),
    ("they resolved my complaint effectively", ["Customer_Service"]),
    ("I had to contact support multiple times", ["Customer_Service"]),
    ("the support team was unresponsive", ["Customer_Service"]),
    ("customer service exceeded my expectations", ["Customer_Service"]),
    ("the issue was not resolved satisfactorily", ["Customer_Service"]),
    ("the product quality is excellent", ["Product_Quality"]),
    ("really impressed with the build quality", ["Product_Quality"]),
    ("the item feels premium and well made", ["Product_Quality"]),
    ("quality exceeded my expectations", ["Product_Quality"]),
    ("very durable and sturdy product", ["Product_Quality"]),
    ("the finish and material are top notch", ["Product_Quality"]),
    ("it feels solid and reliable", ["Product_Quality"]),
    ("great craftsmanship", ["Product_Quality"]),
    ("the product feels cheap and poorly made", ["Product_Quality"]),
    ("quality is disappointing", ["Product_Quality"]),
    ("it broke after a few uses", ["Product_Quality"]),
    ("the material is not durable", ["Product_Quality"]),
    ("very low quality product", ["Product_Quality"]),
    ("it stopped working within days", ["Product_Quality"]),
    ("the item feels fragile", ["Product_Quality"]),
    ("not satisfied with the quality", ["Product_Quality"]),
    ("the product arrived defective", ["Product_Quality"]),
    ("there were scratches on the item", ["Product_Quality"]),
    ("it was damaged when I opened it", ["Product_Quality"]),
    ("some parts were missing", ["Product_Quality"]),
    ("the product was not functioning properly", ["Product_Quality"]),
    ("it had visible defects", ["Product_Quality"]),
    ("the item was faulty from the start", ["Product_Quality"]),
    ("it has held up well over time", ["Product_Quality"]),
    ("the product is still working perfectly", ["Product_Quality"]),
    ("it started showing issues after a week", ["Product_Quality"]),
    ("not durable for long term use", ["Product_Quality"]),
    ("it wears out quickly", ["Product_Quality"]),
    ("quality degrades over time", ["Product_Quality"]),
    ("I expected better quality for this product", ["Product_Quality"]),
    ("doesn't match the description in terms of quality", ["Product_Quality"]),
    ("quality is not as advertised", ["Product_Quality"]),
    ("it turned out better than expected", ["Product_Quality"]),
    ("the actual product is better than the pictures", ["Product_Quality"]),
    ("better quality than similar products", ["Product_Quality"]),
    ("quality is worse compared to other brands", ["Product_Quality"]),
    ("not as good as previous versions", ["Product_Quality"]),
    ("this one feels more durable than others", ["Product_Quality"]),
    ("it works exactly as expected", ["Product_Quality"]),
    ("the performance is reliable", ["Product_Quality"]),
    ("it doesn't function properly", ["Product_Quality"]),
    ("performance is inconsistent", ["Product_Quality"]),
    ("the product does not meet expectations", ["Product_Quality"]),
    ("quality is okay, nothing special", ["Product_Quality"]),
    ("decent quality for everyday use", ["Product_Quality"]),
    ("it's acceptable for the price", ["Product_Quality"]),
    ("average build quality", ["Product_Quality"]),
    ("trouble placing order", "App_Experience"),
("issue during checkout", "App_Experience"),
("problem while ordering", "App_Experience"),

    ]

  