data = [
    ("Delivery was late", ["Delivery"]),
    ("product quality is amazing", ["Product_Quality"]),
    ("Price is too high", ["Price"]),
    ("Packaging was bad", ["Packaging"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("app is slow", ["App_Experience"]),
    ("Delivery was late", ["Delivery"]),
("Delivery arrived late", ["Delivery"]),
("my Delivery was delayed", ["Delivery"]),
("late Delivery service", ["Delivery"]),
("Delivery took too long", ["Delivery"]),
("Delivery was late", ["Delivery"]),
("Delivery arrived late", ["Delivery"]),
("my Delivery was delayed", ["Delivery"]),
("late Delivery service", ["Delivery"]),
("Delivery took too long", ["Delivery"]),
("Delivery was slow", ["Delivery"]),
("slow Delivery", ["Delivery"]),
("shipping was very slow", ["Delivery"]),
("Delivery took many days", ["Delivery"]),
("Delivery is extremely slow", ["Delivery"]),
("i received my order late", ["Delivery"]),
("my order came very late", ["Delivery"]),
("order Delivery was delayed", ["Delivery"]),
("got my order on time", ["Delivery"]),
("order arrived quickly", ["Delivery"]),
("product is good", ["Product_Quality"]),
("product quality is good", ["Product_Quality"]),
("product is bad", ["Product_Quality"]),
("poor product quality", ["Product_Quality"]),
("excellent product quality", ["Product_Quality"]),
("product is good", ["Product_Quality"]),
("product quality is good", ["Product_Quality"]),
("product is bad", ["Product_Quality"]),
("poor product quality", ["Product_Quality"]),
("excellent product quality", ["Product_Quality"]),
("very good quality product", ["Product_Quality"]),
("amazing product quality", ["Product_Quality"]),
("excellent item", ["Product_Quality"]),
("product is शानदार", ["Product_Quality"]),
("really satisfied with the product", ["Product_Quality"]),
("product quality is poor", ["Product_Quality"]),
("very bad product", ["Product_Quality"]),
("item is खराब", ["Product_Quality"]),
("product broke quickly", ["Product_Quality"]),
("low quality item", ["Product_Quality"]),
("product quality is poor", ["Product_Quality"]),
("very bad product", ["Product_Quality"]),
("item is खराब", ["Product_Quality"]),
("product broke quickly", ["Product_Quality"]),
("low quality item", ["Product_Quality"]),
("product stopped working", ["Product_Quality"]),
("item is not working properly", ["Product_Quality"]),
("product is defective", ["Product_Quality"]),
("product is damaged", ["Product_Quality"]),
("item doesn't function well", ["Product_Quality"]),
("this product is worth it", ["Product_Quality"]),
("not satisfied with the product", ["Product_Quality"]),
("product quality could be better", ["Product_Quality"]),
("i love this product", ["Product_Quality"]),
("this item is terrible", ["Product_Quality"]),
("Price is high", ["Price"]),
("Price is too high", ["Price"]),
("Price is low", ["Price"]),
("Price is reasonable", ["Price"]),
("Price is affordable", ["Price"]),
("very expensive product", ["Price"]),
("too costly", ["Price"]),
("Price is not worth it", ["Price"]),
("overPriced item", ["Price"]),
("high Price for this product", ["Price"]),
("cheap product", ["Price"]),
("very affordable Price", ["Price"]),
("low cost item", ["Price"]),
("budget friendly product", ["Price"]),
("great Price for the product", ["Price"]),
("value for money", ["Price"]),
("not worth the Price", ["Price"]),
("worth the money", ["Price"]),
("good value for money", ["Price"]),
("bad value for money", ["Price"]),
("this product is too expensive", ["Price"]),
("i think the Price is fair", ["Price"]),
("Price could be lower", ["Price"]),
("not satisfied with the Price", ["Price"]),
("Price is justified", ["Price"]),
("Packaging was good", ["Packaging"]),
("Packaging was bad", ["Packaging"]),
("poor Packaging", ["Packaging"]),
("excellent Packaging", ["Packaging"]),
("Packaging was good", ["Packaging"]),
("Packaging was bad", ["Packaging"]),
("poor Packaging", ["Packaging"]),
("excellent Packaging", ["Packaging"]),
("very good Packaging", ["Packaging"]),
("amazing Packaging", ["Packaging"]),
("excellent box", ["Packaging"]),
("package was damaged", ["Packaging"]),
("box was broken", ["Packaging"]),
("item was not well packaged", ["Packaging"]),
("package arrived in good condition", ["Packaging"]),
("box was intact and secure", ["Packaging"]),
("customer support was helpful", ["Customer_Service"]),
("customer support was bad", ["Customer_Service"]),
("poor customer service", ["Customer_Service"]),
("excellent customer service", ["Customer_Service"]),
("customer support was helpful", ["Customer_Service"]),
("customer support was bad", ["Customer_Service"]),
("poor customer service", ["Customer_Service"]),
("excellent customer service", ["Customer_Service"]),
("very good customer service", ["Customer_Service"]),
("amazing customer support", ["Customer_Service"]),
("support team was excellent", ["Customer_Service"]),
("support team was unhelpful", ["Customer_Service"]),
("not satisfied with customer service", ["Customer_Service"]),
("i had a great experience with customer support", ["Customer_Service"]),
("the support team was terrible", ["Customer_Service"]),
("app is slow", ["App_Experience"]),
 ("Delivery was late", ["Delivery"]),
    ("product quality is amazing", ["Product_Quality"]),
    ("Price is too high", ["Price"]),
    ("Packaging was bad", ["Packaging"]),
    ("customer support was helpful", ["Customer_Service"]),
    ("app is slow", ["App_Experience"]),
    ("Delivery was late", ["Delivery"]),
("Delivery arrived late", ["Delivery"]),
("my Delivery was delayed", ["Delivery"]),
("late Delivery service", ["Delivery"]),
("Delivery took too long", ["Delivery"]),
("Delivery was late", ["Delivery"]),
("Delivery arrived late", ["Delivery"]),
("my Delivery was delayed", ["Delivery"]),
("late Delivery service", ["Delivery"]),
("Delivery took too long", ["Delivery"]),
("Delivery was slow", ["Delivery"]),
("slow Delivery", ["Delivery"]),
("shipping was very slow", ["Delivery"]),
("Delivery took many days", ["Delivery"]),
("Delivery is extremely slow", ["Delivery"]),
("i received my order late", ["Delivery"]),
("my order came very late", ["Delivery"]),
("order Delivery was delayed", ["Delivery"]),
("got my order on time", ["Delivery"]),
("order arrived quickly", ["Delivery"]),
("product is good", ["Product_Quality"]),
("product quality is good", ["Product_Quality"]),
("product is bad", ["Product_Quality"]),
("poor product quality", ["Product_Quality"]),
("excellent product quality", ["Product_Quality"]),
("product is good", ["Product_Quality"]),
("product quality is good", ["Product_Quality"]),
("product is bad", ["Product_Quality"]),
("poor product quality", ["Product_Quality"]),
("excellent product quality", ["Product_Quality"]),
("very good quality product", ["Product_Quality"]),
("amazing product quality", ["Product_Quality"]),
("excellent item", ["Product_Quality"]),
("product is शानदार", ["Product_Quality"]),
("really satisfied with the product", ["Product_Quality"]),
("product quality is poor", ["Product_Quality"]),
("very bad product", ["Product_Quality"]),
("item is खराब", ["Product_Quality"]),
("product broke quickly", ["Product_Quality"]),
("low quality item", ["Product_Quality"]),
("product quality is poor", ["Product_Quality"]),
("very bad product", ["Product_Quality"]),
("item is खराब", ["Product_Quality"]),
("product broke quickly", ["Product_Quality"]),
("low quality item", ["Product_Quality"]),
("product stopped working", ["Product_Quality"]),
("item is not working properly", ["Product_Quality"]),
("product is defective", ["Product_Quality"]),
("product is damaged", ["Product_Quality"]),
("item doesn't function well", ["Product_Quality"]),
("this product is worth it", ["Product_Quality"]),
("not satisfied with the product", ["Product_Quality"]),
("product quality could be better", ["Product_Quality"]),
("i love this product", ["Product_Quality"]),
("this item is terrible", ["Product_Quality"]),
("Price is high", ["Price"]),
("Price is too high", ["Price"]),
("Price is low", ["Price"]),
("Price is reasonable", ["Price"]),
("Price is affordable", ["Price"]),
("very expensive product", ["Price"]),
("too costly", ["Price"]),
("Price is not worth it", ["Price"]),
("overPriced item", ["Price"]),
("high Price for this product", ["Price"]),
("cheap product", ["Price"]),
("very affordable Price", ["Price"]),
("low cost item", ["Price"]),
("budget friendly product", ["Price"]),
("great Price for the product", ["Price"]),
("value for money", ["Price"]),
("not worth the Price", ["Price"]),
("worth the money", ["Price"]),
("good value for money", ["Price"]),
("bad value for money", ["Price"]),
("this product is too expensive", ["Price"]),
("i think the Price is fair", ["Price"]),
("Price could be lower", ["Price"]),
("not satisfied with the Price", ["Price"]),
("Price is justified", ["Price"]),
("Packaging was good", ["Packaging"]),
("Packaging was bad", ["Packaging"]),
("poor Packaging", ["Packaging"]),
("excellent Packaging", ["Packaging"]),
("Packaging was good", ["Packaging"]),
("Packaging was bad", ["Packaging"]),
("poor Packaging", ["Packaging"]),
("excellent Packaging", ["Packaging"]),
("very good Packaging", ["Packaging"]),
("amazing Packaging", ["Packaging"]),
("excellent box", ["Packaging"]),
("package was damaged", ["Packaging"]),
("box was broken", ["Packaging"]),
("item was not well packaged", ["Packaging"]),
("package arrived in good condition", ["Packaging"]),
("box was intact and secure", ["Packaging"]),
("customer support was helpful", ["Customer_Service"]),
("customer support was bad", ["Customer_Service"]),
("poor customer service", ["Customer_Service"]),
("excellent customer service", ["Customer_Service"]),
("customer support was helpful", ["Customer_Service"]),
("customer support was bad", ["Customer_Service"]),
("poor customer service", ["Customer_Service"]),
("excellent customer service", ["Customer_Service"]),
("very good customer service", ["Customer_Service"]),
("amazing customer support", ["Customer_Service"]),
("support team was excellent", ["Customer_Service"]),
("support team was unhelpful", ["Customer_Service"]),
("not satisfied with customer service", ["Customer_Service"]),
("i had a great experience with customer support", ["Customer_Service"]),
("the support team was terrible", ["Customer_Service"]),
("app is slow", ["App_Experience"]),
("app is fast", ["App_Experience"]),
("app is unresponsive", ["App_Experience"]),
("app is user-friendly", ["App_Experience"]),
("app is slow", ["App_Experience"]),
("app is fast", ["App_Experience"]),
("app is unresponsive", ["App_Experience"]),
("app is user-friendly", ["App_Experience"]),
("very slow app performance", ["App_Experience"]),
("amazing app experience", ["App_Experience"]),
("the app crashes frequently", ["App_Experience"]),
("the app is easy to navigate", ["App_Experience"]),
("website is slow", ["App_Experience"]),
("website is fast", ["App_Experience"]),    
("website is unresponsive", ["App_Experience"]),
("website is user-friendly", ["App_Experience"]),
("website is slow", ["App_Experience"]),
("website is fast", ["App_Experience"]),    
("website is unresponsive", ["App_Experience"]),
("website is user-friendly", ["App_Experience"]),
("very slow website performance", ["App_Experience"]),
("amazing website experience", ["App_Experience"]),
("the website crashes frequently", ["App_Experience"]),
("the website is easy to navigate", ["App_Experience"]),
("website is very slow", ["App_Experience"]),
("app is very slow", ["App_Experience"]),   
("app is extremely slow", ["App_Experience"]),
("website is extremely slow", ["App_Experience"])
]